Closes #1219: fixes a 'null' toast on autofill failure on Android 11
mozilla-lockwise/lockwise-android pull request #1224
Opened 2020-09-21 21:11 UTC by Baron-Severin

Fixes #1219

## Testing and Review Notes

- Use device running Android 11 (I was unable to repro on emulator)
- Install master Lockwise
- Set Lockwise as autofill provider
- Close and open Play Store app
- Select search bar at top of screen
EXPECT toast with text "null"
- Install `1219-fix-null-toast` Lockwise
- Close and open Play Store app
- Select search bar at top of screen
EXPECT no toast

## Screenshots or Videos

### master
<img src="https://user-images.githubusercontent.com/13170306/93821701-c9e49380-fc13-11ea-8289-262cc017fd6f.gif" height="600px"/>

### 1219 fix
<img src="https://user-images.githubusercontent.com/13170306/93821718-d0730b00-fc13-11ea-84f4-1b7fcbd0a55e.gif" height="600px"/>

## To Do

- [X] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [X] double check the original issue to confirm it is fully satisfied
- [X] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - Unfeasible
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
  - Not applicable, no UI changes
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [X] check on the [accessibility](https://mozilla-lockwise.github.io/lockwise-android/accessibility/) of any added UI
  - None

2020-09-22 14:41 UTC, Baron-Severin commented
I do have one open question here. I'm not clear on what calling callback.onFailure is supposed to do.  I didn't notice any difference on testing.  If it's important, we could do a version check and only skip it on Android 11.

Maybe that's the more responsible thing to do anyway....

2020-09-22 19:15 UTC, eliserichards requested changes
Looks awesome! Just one nit and this can be merged.

2020-09-22 19:15 UTC, eliserichards commented on app/src/main/java/mozilla/lockbox/LockboxAutofillService.kt
> +     * instead.
Can you add the link to the google issue in this comment?

2020-09-22 21:06 UTC, eliserichards approved these changes
Great job! 🔥

2020-09-22 23:23 UTC, merged

2020-10-28 15:00 UTC, Webbeh commented
Great ! Just noticed the issue came from Lockwise.

Any ETA on it being merged ?

2020-11-15 06:54 UTC, Webbeh commented
https://github.com/mozilla-lockwise/lockwise-android/issues/1219#issuecomment-727525094
Self-signed APK with the fix implemented for anyone willing to try and report bugs for that version.

2020-12-20 17:05 UTC, donm527 commented
Thank you for the reply and offering a solution. So, if I am reading correctly, this bug has been reported as far back as September and no official update of the app from Mozilla?? 

Thanks though and I may try the unsigned copy. When they do update through Google Play, will your copy update or do I have to uninstall and re-download from the Play Store? That would mean I'd have to keep an eye for updates on the store since your copy will not notify me in Play Store?

2020-12-20 17:44 UTC, Webbeh commented
There is an official update that has been sent and is signed in the releases.
https://github.com/mozilla-lockwise/lockwise-android/releases/tag/release-v4.0.3

It's simply not on the play store for the sole reason that Google updated their play store minimum required API and this is still not 100% up to date.

The app is working well and after the fix, I've been using it since it came out.

2020-12-20 17:51 UTC, donm527 commented
Oh OK, great! Thanks for the clarity. 

Will this version I sideload see and update any future updates that appear in Play Store or will I have to uninstall and download the new version when I see one has been updated on the store?

TIA!

2021-01-03 19:31 UTC, donm527 commented
Will this version I sideload see and update any future updates that appear in Play Store or will I have to uninstall and download the new version when I see one has been updated on the store?